import java.io.File;


public class Pokemon6G extends Pokemon {
	
	public Pokemon6G (int numero, String[] noms, Type[] type, Stat stats, File image, int nbevolution, boolean estuneevolution, Talent[] talents, int[] famille){
		super(numero,noms,type,stats,image,nbevolution,estuneevolution,talents,famille);
	}
	
	public static Pokemon  marisson  = new Pokemon (650,new String[] { "Marisson" , "Chespin"},new Type[]{Type.plante,Type.zero},Stat.allstats[650], new File ("images/pokemons/650.png"),1,false, new Talent[]{Talent.engrais,Talent.zero,Talent.pareballes}, new int[]{651,652});
	public static Pokemon  boguerisse  = new Pokemon (651,new String[] { "Boguerisse" , "Quilladin"},new Type[]{Type.plante,Type.zero},Stat.allstats[651], new File ("images/pokemons/651.png"),1,true, new Talent[]{Talent.engrais,Talent.zero,Talent.pareballes}, new int[]{650,652});
	public static Pokemon  blindepique  = new Pokemon (652,new String[] { "Blindepique" , "Chesnaught"},new Type[]{Type.plante,Type.combat},Stat.allstats[652], new File ("images/pokemons/652.png"),0,true, new Talent[]{Talent.engrais,Talent.zero,Talent.pareballes}, new int[]{651,652});
	public static Pokemon  feunnec  = new Pokemon (653,new String[] { "Feunnec" , "Fennekin"},new Type[]{Type.feu,Type.zero},Stat.allstats[653], new File ("images/pokemons/653.png"),1,false, new Talent[]{Talent.brasier,Talent.zero,Talent.magicien}, new int[]{654,655});
	public static Pokemon  roussil  = new Pokemon (654,new String[] { "Roussil" , "Braixen"},new Type[]{Type.feu,Type.zero},Stat.allstats[654], new File ("images/pokemons/654.png"),1,true, new Talent[]{Talent.brasier,Talent.zero,Talent.magicien}, new int[]{653,655});
	public static Pokemon  goupelin  = new Pokemon (655,new String[] { "Goupelin" , "Delphox"},new Type[]{Type.feu,Type.psy},Stat.allstats[655], new File ("images/pokemons/655.png"),0,true, new Talent[]{Talent.brasier,Talent.zero,Talent.magicien}, new int[]{653,654});
	public static Pokemon  grenousse  = new Pokemon (656,new String[] { "Grenousse" , "Froakie"},new Type[]{Type.eau,Type.zero},Stat.allstats[656], new File ("images/pokemons/656.png"),1,false, new Talent[]{Talent.torrent,Talent.zero,Talent.proteen}, new int[]{657,658});
	public static Pokemon  croaporal  = new Pokemon (657,new String[] { "Croaporal" , "Frogadier"},new Type[]{Type.eau,Type.zero},Stat.allstats[657], new File ("images/pokemons/657.png"),1,true, new Talent[]{Talent.torrent,Talent.zero,Talent.proteen}, new int[]{656,658});
	public static Pokemon  amphinobi  = new Pokemon (658,new String[] { "Amphinobi" , "Greninja"},new Type[]{Type.eau,Type.tenebres},Stat.allstats[658], new File ("images/pokemons/658.png"),0,true, new Talent[]{Talent.torrent,Talent.zero,Talent.proteen}, new int[]{656,657});
	public static Pokemon  sapereau  = new Pokemon (659,new String[] { "Sapereau" , "Bunnelby"},new Type[]{Type.normal,Type.zero},Stat.allstats[659], new File ("images/pokemons/659.png"),1,false, new Talent[]{Talent.ramassage,Talent.bajoues,Talent.coloforce}, new int[]{660});
	public static Pokemon  excavarenne  = new Pokemon (660,new String[] { "Excavarenne" , "Diggersby"},new Type[]{Type.normal,Type.sol},Stat.allstats[660], new File ("images/pokemons/660.png"),0,true, new Talent[]{Talent.ramassage,Talent.bajoues,Talent.coloforce}, new int[]{659});
	public static Pokemon  passerouge  = new Pokemon (661,new String[] { "Passerouge" , "Fletchling"},new Type[]{Type.normal,Type.vol},Stat.allstats[661], new File ("images/pokemons/661.png"),1,false, new Talent[]{Talent.coeurdecoq,Talent.zero,Talent.ailesbourrasque}, new int[]{662,663});
	public static Pokemon  braisillon  = new Pokemon (662,new String[] { "Braisillon" , "Fletchinder"},new Type[]{Type.feu,Type.vol},Stat.allstats[662], new File ("images/pokemons/662.png"),1,true, new Talent[]{Talent.corpsardent,Talent.zero,Talent.ailesbourrasque}, new int[]{662,664});
	public static Pokemon  flambusard  = new Pokemon (663,new String[] { "Flambusard" , "Talonflame"},new Type[]{Type.feu,Type.vol},Stat.allstats[663], new File ("images/pokemons/663.png"),0,true, new Talent[]{Talent.corpsardent,Talent.zero,Talent.ailesbourrasque}, new int[]{662,663});
	public static Pokemon  lepidonille  = new Pokemon (664,new String[] { "Lepidonille" , "Scatterbug"},new Type[]{Type.insecte,Type.zero},Stat.allstats[664], new File ("images/pokemons/664.png"),1,false, new Talent[]{Talent.oeilcompose,Talent.ecranpoudre,Talent.gardeamie}, new int[]{665,666});
	public static Pokemon  peregrain  = new Pokemon (665,new String[] { "Peregrain" , "Spewpa"},new Type[]{Type.insecte,Type.zero},Stat.allstats[665], new File ("images/pokemons/665.png"),1,true, new Talent[]{Talent.mue,Talent.zero,Talent.gardeamie}, new int[]{664,666});
	public static Pokemon  prismillon  = new Pokemon (666,new String[] { "Prismillon" , "Vivillon"},new Type[]{Type.insecte,Type.vol},Stat.allstats[666], new File ("images/pokemons/666.png"),0,true, new Talent[]{Talent.oeilcompose,Talent.ecranpoudre,Talent.gardeamie}, new int[]{664,665});
	public static Pokemon  helionceau  = new Pokemon (667,new String[] { "Helionceau" , "Litleo"},new Type[]{Type.feu,Type.normal},Stat.allstats[667], new File ("images/pokemons/667.png"),1,false, new Talent[]{Talent.rivalite,Talent.tension,Talent.impudence}, new int[]{668});
	public static Pokemon  nemelios  = new Pokemon (668,new String[] { "Nemelios" , "Pyroar"},new Type[]{Type.feu,Type.normal},Stat.allstats[668], new File ("images/pokemons/668.png"),0,true, new Talent[]{Talent.rivalite,Talent.tension,Talent.impudence}, new int[]{667});
	public static Pokemon  flabebe  = new Pokemon (669,new String[] { "Flab�b�" , "Flab�b�"},new Type[]{Type.fee,Type.zero},Stat.allstats[669], new File ("images/pokemons/669.png"),1,false, new Talent[]{Talent.floravoile,Talent.zero,Talent.symbiose}, new int[]{670,671});
	public static Pokemon  floette  = new Pokemon (670,new String[] { "Floette" , "Floette"},new Type[]{Type.fee,Type.zero},Stat.allstats[670], new File ("images/pokemons/670.png"),1,true, new Talent[]{Talent.floravoile,Talent.zero,Talent.symbiose}, new int[]{669,671});
	public static Pokemon  florges  = new Pokemon (671,new String[] { "Florges" , "Florges"},new Type[]{Type.fee,Type.zero},Stat.allstats[671], new File ("images/pokemons/671.png"),0,true, new Talent[]{Talent.floravoile,Talent.zero,Talent.symbiose}, new int[]{669,670});
	public static Pokemon  cabriolaine  = new Pokemon (672,new String[] { "Cabriolaine" , "Skiddo"},new Type[]{Type.plante,Type.zero},Stat.allstats[672], new File ("images/pokemons/672.png"),1,false, new Talent[]{Talent.herbivore,Talent.zero,Talent.toisonherbue}, new int[]{673});
	public static Pokemon  chevroum  = new Pokemon (673,new String[] { "Chevroum" , "Gogoat"},new Type[]{Type.plante,Type.zero},Stat.allstats[673], new File ("images/pokemons/673.png"),0,true, new Talent[]{Talent.herbivore,Talent.zero,Talent.toisonherbue}, new int[]{672});
	public static Pokemon  pandespiegle  = new Pokemon (674,new String[] { "Pandespiegle" , "Pancham"},new Type[]{Type.combat,Type.zero},Stat.allstats[674], new File ("images/pokemons/674.png"),1,false, new Talent[]{Talent.brisemoule,Talent.poingdefer,Talent.querelleur}, new int[]{675});
	public static Pokemon  pandarbare  = new Pokemon (675,new String[] { "Pandarbare" , "Pangoro"},new Type[]{Type.combat,Type.tenebres},Stat.allstats[675], new File ("images/pokemons/675.png"),0,true, new Talent[]{Talent.brisemoule,Talent.poingdefer,Talent.querelleur}, new int[]{674});
	public static Pokemon  couafarel  = new Pokemon (676,new String[] { "Couafarel" , "Furfrou"},new Type[]{Type.normal,Type.zero},Stat.allstats[676], new File ("images/pokemons/676.png"),0,false, new Talent[]{Talent.toisonepaisse,Talent.zero,Talent.zero}, new int[]{});
	public static Pokemon  psystigri  = new Pokemon (677,new String[] { "Psystigri" , "Espurr"},new Type[]{Type.psy,Type.zero},Stat.allstats[677], new File ("images/pokemons/677.png"),1,false, new Talent[]{Talent.regardvif,Talent.infiltration,Talent.tempoperso}, new int[]{678});
	public static Pokemon  mistigrix  = new Pokemon (678,new String[] { "Mistigrix" , "Meowstic"},new Type[]{Type.psy,Type.zero},Stat.allstats[678], new File ("images/pokemons/678.png"),0,true, new Talent[]{Talent.regardvif,Talent.infiltration,Talent.farceur}, new int[]{677});
	public static Pokemon  monorpale  = new Pokemon (679,new String[] { "Monorpale" , "Honedge"},new Type[]{Type.acier,Type.spectre},Stat.allstats[679], new File ("images/pokemons/679.png"),1,false, new Talent[]{Talent.annulegarde,Talent.zero,Talent.zero}, new int[]{680,681});
	public static Pokemon  dimocles  = new Pokemon (680,new String[] { "Dimocles" , "Doublade"},new Type[]{Type.acier,Type.spectre},Stat.allstats[680], new File ("images/pokemons/680.png"),1,true, new Talent[]{Talent.annulegarde,Talent.zero,Talent.zero}, new int[]{679,681});
	public static Pokemon  exagide  = new Pokemon (681,new String[] { "Exagide" , "Aegislash"},new Type[]{Type.acier,Type.spectre},Stat.allstats[681], new File ("images/pokemons/681.png"),0,true, new Talent[]{Talent.declictactique,Talent.zero,Talent.zero}, new int[]{679,680});
	public static Pokemon  fluvetin  = new Pokemon (682,new String[] { "Fluvetin" , "Spritzee"},new Type[]{Type.fee,Type.zero},Stat.allstats[682], new File ("images/pokemons/682.png"),1,false, new Talent[]{Talent.coeursoin,Talent.zero,Talent.aromavoile}, new int[]{683});
	public static Pokemon  cocotine  = new Pokemon (683,new String[] { "Cocotine" , "Aromatisse"},new Type[]{Type.fee,Type.zero},Stat.allstats[683], new File ("images/pokemons/683.png"),0,true, new Talent[]{Talent.coeursoin,Talent.zero,Talent.aromavoile}, new int[]{682});
	public static Pokemon  sucroquin  = new Pokemon (684,new String[] { "Sucroquin" , "Swirlix"},new Type[]{Type.fee,Type.zero},Stat.allstats[684], new File ("images/pokemons/684.png"),1,false, new Talent[]{Talent.glucovoile,Talent.zero,Talent.delestage}, new int[]{685});
	public static Pokemon  cupcanaille  = new Pokemon (685,new String[] { "Cupcanaille" , "Slurpuff"},new Type[]{Type.fee,Type.zero},Stat.allstats[685], new File ("images/pokemons/685.png"),0,true, new Talent[]{Talent.glucovoile,Talent.zero,Talent.delestage}, new int[]{684});
	public static Pokemon  sepiatop  = new Pokemon (686,new String[] { "Sepiatop" , "Inkay"},new Type[]{Type.psy,Type.tenebres},Stat.allstats[686], new File ("images/pokemons/686.png"),1,false, new Talent[]{Talent.ventouse,Talent.contestation,Talent.infiltration}, new int[]{687});
	public static Pokemon  sepiatroce  = new Pokemon (687,new String[] { "Sepiatroce" , "Malamar"},new Type[]{Type.psy,Type.tenebres},Stat.allstats[687], new File ("images/pokemons/687.png"),0,true, new Talent[]{Talent.ventouse,Talent.contestation,Talent.infiltration}, new int[]{686});
	public static Pokemon  opermine  = new Pokemon (688,new String[] { "Opermine" , "Binacle"},new Type[]{Type.eau,Type.roche},Stat.allstats[688], new File ("images/pokemons/688.png"),1,false, new Talent[]{Talent.sniper,Talent.griffedure,Talent.pickpocket}, new int[]{689});
	public static Pokemon  golgopathe  = new Pokemon (689,new String[] { "Golgopathe" , "Barbaracle"},new Type[]{Type.eau,Type.roche},Stat.allstats[689], new File ("images/pokemons/689.png"),0,true, new Talent[]{Talent.sniper,Talent.griffedure,Talent.pickpocket}, new int[]{688});
	public static Pokemon  venalgue  = new Pokemon (690,new String[] { "Venalgue" , "Skrelp"},new Type[]{Type.eau,Type.poison},Stat.allstats[690], new File ("images/pokemons/690.png"),1,false, new Talent[]{Talent.pointpoison,Talent.toxitouche,Talent.adaptabilite}, new int[]{691});
	public static Pokemon  kravarech  = new Pokemon (691,new String[] { "Kravarech" , "Dragalge"},new Type[]{Type.dragon,Type.poison},Stat.allstats[691], new File ("images/pokemons/691.png"),0,true, new Talent[]{Talent.pointpoison,Talent.toxitouche,Talent.adaptabilite}, new int[]{690});
	public static Pokemon  flingouste  = new Pokemon (692,new String[] { "Flingouste" , "Clauncher"},new Type[]{Type.eau,Type.zero},Stat.allstats[692], new File ("images/pokemons/692.png"),1,false, new Talent[]{Talent.megablaster,Talent.zero,Talent.zero}, new int[]{693});
	public static Pokemon  gamblast  = new Pokemon (693,new String[] { "Gamblast" , "Clawitzer"},new Type[]{Type.eau,Type.zero},Stat.allstats[693], new File ("images/pokemons/693.png"),0,true, new Talent[]{Talent.megablaster,Talent.zero,Talent.zero}, new int[]{692});
	public static Pokemon  galvaran  = new Pokemon (694,new String[] { "Galvaran" , "Helioptile"},new Type[]{Type.electrique,Type.normal},Stat.allstats[694], new File ("images/pokemons/694.png"),1,false, new Talent[]{Talent.voilesable,Talent.peauseche,Talent.forcesoleil}, new int[]{695});
	public static Pokemon  iguolta  = new Pokemon (695,new String[] { "Iguolta" , "Heliolisk"},new Type[]{Type.electrique,Type.normal},Stat.allstats[695], new File ("images/pokemons/695.png"),0,true, new Talent[]{Talent.voilesable,Talent.peauseche,Talent.forcesoleil}, new int[]{694});
	public static Pokemon  ptyranidur  = new Pokemon (696,new String[] { "Ptyranidur" , "Tyrunt"},new Type[]{Type.roche,Type.dragon},Stat.allstats[696], new File ("images/pokemons/696.png"),1,false, new Talent[]{Talent.prognathe,Talent.zero,Talent.fermete}, new int[]{697});
	public static Pokemon  rexillius  = new Pokemon (697,new String[] { "Rexillius" , "Tyrantrum"},new Type[]{Type.roche,Type.dragon},Stat.allstats[697], new File ("images/pokemons/697.png"),0,true, new Talent[]{Talent.prognathe,Talent.zero,Talent.tetederoc}, new int[]{696});
	public static Pokemon  amagara  = new Pokemon (698,new String[] { "Amagara" , "Amaura"},new Type[]{Type.roche,Type.glace},Stat.allstats[698], new File ("images/pokemons/698.png"),1,false, new Talent[]{Talent.peaugelee,Talent.zero,Talent.alerteneige}, new int[]{699});
	public static Pokemon  dragmara  = new Pokemon (699,new String[] { "Dragmara" , "Aurorus"},new Type[]{Type.roche,Type.glace},Stat.allstats[699], new File ("images/pokemons/699.png"),0,true, new Talent[]{Talent.peaugelee,Talent.zero,Talent.alerteneige}, new int[]{698});
	public static Pokemon  nymphali  = new Pokemon (700,new String[] { "Nymphali" , "Sylveon"},new Type[]{Type.fee,Type.zero},Stat.allstats[700], new File ("images/pokemons/700.png"),0,true, new Talent[]{Talent.jolisourire,Talent.zero,Talent.peaufeerique}, new int[]{133,134,135,136,196,197,470,471});
	public static Pokemon  brutalibre  = new Pokemon (701,new String[] { "Brutalibre" , "Hawlucha"},new Type[]{Type.combat,Type.vol},Stat.allstats[701], new File ("images/pokemons/701.png"),0,false, new Talent[]{Talent.echauffement,Talent.delestage,Talent.brisemoule}, new int[]{});
	public static Pokemon  dedenne  = new Pokemon (702,new String[] { "Dedenne" , "Dedenne"},new Type[]{Type.electrique,Type.fee},Stat.allstats[702], new File ("images/pokemons/702.png"),0,false, new Talent[]{Talent.ramassage,Talent.bajoues,Talent.plus}, new int[]{});
	public static Pokemon  strassie  = new Pokemon (703,new String[] { "Strassie" , "Carbink"},new Type[]{Type.fee,Type.roche},Stat.allstats[703], new File ("images/pokemons/703.png"),0,false, new Talent[]{Talent.corpssain,Talent.zero,Talent.fermete}, new int[]{});
	public static Pokemon  mucuscule  = new Pokemon (704,new String[] { "Mucuscule" , "Goomy"},new Type[]{Type.dragon,Type.zero},Stat.allstats[704], new File ("images/pokemons/704.png"),1,false, new Talent[]{Talent.hydratation,Talent.herbivore,Talent.poisseux}, new int[]{705,706});
	public static Pokemon  colimucus  = new Pokemon (705,new String[] { "Colimucus" , "Sliggoo"},new Type[]{Type.dragon,Type.zero},Stat.allstats[705], new File ("images/pokemons/705.png"),1,true, new Talent[]{Talent.hydratation,Talent.herbivore,Talent.poisseux}, new int[]{704,706});
	public static Pokemon  muplodocus  = new Pokemon (706,new String[] { "Muplodocus" , "Goodra"},new Type[]{Type.dragon,Type.zero},Stat.allstats[706], new File ("images/pokemons/706.png"),0,true, new Talent[]{Talent.hydratation,Talent.herbivore,Talent.poisseux}, new int[]{704,705});
	public static Pokemon  trousselin  = new Pokemon (707,new String[] { "Trousselin" , "Klefki"},new Type[]{Type.acier,Type.fee},Stat.allstats[707], new File ("images/pokemons/707.png"),0,false, new Talent[]{Talent.farceur,Talent.zero,Talent.magicien}, new int[]{});
	public static Pokemon  brocelome  = new Pokemon (708,new String[] { "Brocelome" , "Phantump"},new Type[]{Type.spectre,Type.plante},Stat.allstats[708], new File ("images/pokemons/708.png"),1,false, new Talent[]{Talent.medicnature,Talent.fouille,Talent.recolte}, new int[]{709});
	public static Pokemon  desseliande  = new Pokemon (709,new String[] { "Desseliande" , "Trevenant"},new Type[]{Type.spectre,Type.plante},Stat.allstats[709], new File ("images/pokemons/709.png"),0,true, new Talent[]{Talent.medicnature,Talent.fouille,Talent.recolte}, new int[]{708});
	public static Pokemon  pitrouille  = new Pokemon (710,new String[] { "Pitrouille" , "Pumpkaboo"},new Type[]{Type.spectre,Type.plante},Stat.allstats[710], new File ("images/pokemons/710.png"),1,false, new Talent[]{Talent.ramassage,Talent.fouille,Talent.insomnia}, new int[]{711});
	public static Pokemon  banshitrouye  = new Pokemon (711,new String[] { "Banshitrouye" , "Gourgeist"},new Type[]{Type.spectre,Type.plante},Stat.allstats[711], new File ("images/pokemons/711.png"),0,true, new Talent[]{Talent.ramassage,Talent.fouille,Talent.insomnia}, new int[]{710});
	public static Pokemon  grelacon  = new Pokemon (712,new String[] { "Grelacon" , "Bergmite"},new Type[]{Type.glace,Type.zero},Stat.allstats[712], new File ("images/pokemons/712.png"),1,false, new Talent[]{Talent.tempoperso,Talent.corpsgel,Talent.fermete}, new int[]{713});
	public static Pokemon  seracrawl  = new Pokemon (713,new String[] { "Seracrawl" , "Avalugg"},new Type[]{Type.glace,Type.zero},Stat.allstats[713], new File ("images/pokemons/713.png"),0,true, new Talent[]{Talent.tempoperso,Talent.corpsgel,Talent.fermete}, new int[]{712});
	public static Pokemon  sonistrelle  = new Pokemon (714,new String[] { "Sonistrelle" , "Noibat"},new Type[]{Type.vol,Type.dragon},Stat.allstats[714], new File ("images/pokemons/714.png"),1,false, new Talent[]{Talent.fouille,Talent.infiltration,Talent.telepathe}, new int[]{715});
	public static Pokemon  bruyverne  = new Pokemon (715,new String[] { "Bruyverne" , "Noivern"},new Type[]{Type.vol,Type.dragon},Stat.allstats[715], new File ("images/pokemons/715.png"),0,true, new Talent[]{Talent.fouille,Talent.infiltration,Talent.telepathe}, new int[]{714});
	public static Pokemon  xerneas  = new Pokemon (716,new String[] { "Xerneas" , "Xerneas"},new Type[]{Type.fee,Type.zero},Stat.allstats[716], new File ("images/pokemons/716.png"),0,false, new Talent[]{Talent.aurafeerique,Talent.zero,Talent.zero}, new int[]{});
	public static Pokemon  yveltal  = new Pokemon (717,new String[] { "Yveltal" , "Yveltal"},new Type[]{Type.tenebres,Type.vol},Stat.allstats[717], new File ("images/pokemons/717.png"),0,false, new Talent[]{Talent.auratenebreuse,Talent.zero,Talent.zero}, new int[]{});
	public static Pokemon  zygarde  = new Pokemon (718,new String[] { "Zygarde" , "Zygarde"},new Type[]{Type.dragon,Type.sol},Stat.allstats[718], new File ("images/pokemons/718.png"),0,false, new Talent[]{Talent.aurainversee,Talent.zero,Talent.zero}, new int[]{});
	public static Pokemon  diancie  = new Pokemon (719,new String[] { "Diancie" , "Diancie"},new Type[]{Type.roche,Type.fee},Stat.allstats[719], new File ("images/pokemons/719.png"),0,false, new Talent[]{Talent.corpssain,Talent.zero,Talent.zero}, new int[]{});
}

